fission:
  target: "{{ env_var('DBT_TARGET') }}"
  outputs:
    dev:
      type:       snowflake
      account:    "{{ env_var('DBT_DB_ACCOUNT') }}"
      password:   "{{ env_var('DBT_PWD') }}" 
      user:       "{{ env_var('DBT_USER') }}" 
      role:       "{{ env_var('DBT_ROLE') }}" 
      database:   "{{ env_var('DBT_DB') }}" 
      warehouse:  "{{ env_var('DBT_WH') }}" 
      schema:     "{{ env_var('DBT_DB_SCHEMA') }}"
      threads: 4
      client_session_keep_alive: False