name: cd_on_merge
on:
  pull_request:
    types: ['closed']
    branches:
      - 'session_04'
jobs:
  on_merge:
    env:
      DBT_PWD_PROD: ${{ secrets.DBT_PWD_PROD }}
      DBT_PWD: ${{ secrets.DBT_PWD }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SLIM_CI_SERVICE_ACCOUNT_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SLIM_CI_SERVICE_ACCOUNT_SECRET }}
      CI_SCHEMA: "CI_PR_${{ github.event.pull_request.id }}"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Python setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: install-requirements
        run: |
          pip install dbt==0.21.0

          # install packages
          dbt deps

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          # role-to-assume: arn:aws:iam::743265699366:role/Workato_test_access_S3
          aws-region: eu-west-1
          role-duration-seconds: 1200

      - name: Drop CI schema
        run: dbt run-operation drop_schema --profiles-dir . --profile fission

      - name: Fetch prod manifest from s3
        run: aws s3 cp s3://${{ secrets.AWS_S3_BUCKET_NAME }}/manifest.json ./prev_prod_run/manifest.json

      - name: Run seeds
        run: dbt seed --profiles-dir . --profile fission -s state:modified --state ./prev_prod_run --target prod

      - name: Run all models
        run: dbt run --profiles-dir . --profile fission -s state:modified+ --state ./prev_prod_run --defer --target prod

      - name: Run all tests
        run: dbt test --profiles-dir . --profile fission -s state:modified+ --state ./prev_prod_run --defer --target prod

      - name: Generate dbt docs
        run: dbt docs generate --profiles-dir . --profile fission --target prod

      - name: Copy prod artifacts to s3 bucket
        run: |
          aws s3 cp ./target/manifest.json s3://${{ secrets.AWS_S3_BUCKET_NAME }}/manifest.json
          aws s3 cp ./target/catalog.json s3://${{ secrets.AWS_S3_BUCKET_NAME }}/catalog.json
          aws s3 cp ./target/index.html s3://${{ secrets.AWS_S3_BUCKET_NAME }}/index.html
          aws s3 cp ./target/run_results.json s3://${{ secrets.AWS_S3_BUCKET_NAME }}/run_results.json
