name: slim_ci_on_pr
on:
  pull_request:
    branches:
      - 'session_04'
jobs:
  ci_build:
    env:
      DBT_PWD: ${{ secrets.DBT_PWD }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CI_SCHEMA: "CI_PR_${{ github.event.pull_request.id }}"

    runs-on: ubuntu-latest
    steps:
      - name: view the ci_schema var
        run: echo "Schema name = ${{ env.CI_SCHEMA }}"
