name: slim_ci_on_pr
on:
  pull_request:
    branches:
      - 'session_04'
jobs:
  ci_build:
    env:
      DBT_PWD: ${{ secrets.DBT_PWD }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CI_SCHEMA: "CI_PR_${{ github.event.pull_request.id }}"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Python setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: install-requirements
        run: |
          pip install dbt==0.21.0

          # install packages
          dbt deps

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::389099493521:role/bi-learning-slimci-role
          aws-region: us-east-2
          role-duration-seconds: 1200

      - name: Fetch manifest from s3
        run: aws s3 cp s3://bi-learning-slimci/manifest.json ./old_manifest/manifest.json

      - name: Run seeds
        run: dbt seed --profiles-dir . --profile fission -s state:modified --state ./old_manifest

      - name: Run all models
        run: dbt run --profiles-dir . --profile fission -s state:modified+ --state ./old_manifest --defer

      - name: Run all tests
        run: dbt test --exclude test_name:relationships--profiles-dir . --profile fission -s state:modified+ --state ./old_manifest --defer


      - name: Copy manifest.json to s3 bucket
        run: aws s3 cp ./target/manifest.json s3://bi-learning-slimci/manifest.json
