name: slim_ci_on_pr
on:
  pull_request:
    branches:
      - 'session_04'
jobs:
  ci_on_pr:
    env:
      DBT_PWD: ${{ secrets.DBT_PWD }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      PR_ID: ${{ github.event.pull_request.id }}
      CI_SCHEMA: ${{ format('CI_PR_{1}', ${{ env.PR_ID }}) }}

    runs-on: ubuntu-latest
    steps:
      - name: view the PR ID
        run: echo "PR ID = ${{ env.PR_ID }}"

      - name: view schema name
        run: echo "Schema name = ${{ env.CI_SCHEMA }}"
