name: slim_ci
on: 
  push:
    branches:
      - rasti
jobs:
  ci_workflow:
    env:
      DBT_PWD:        ${{  secrets.DBT_PWD }} 

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Python setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: install-requirements
        run: |
          pip install dbt==0.21.0
          
          # install packages
          dbt deps

      - name: Run seeds
        run: dbt seed --profiles-dir . --profile fission
      
      - name: Run all models
        run: dbt run --profiles-dir . --profile fission
      
      - name: Run all tests
        run: dbt test --profiles-dir . --profile fission

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::389099493521:role/bi-learning-slimci-role
          aws-region: us-east-2
      
      - name: Copy manifest.json to s3 bucket
        run: aws s3 cp ./target/manifest.json s3://bi-learning-slimci/manifest.json
