name: ci_on_pr
on:
  pull_request:
    branches:
      - 'session_04'
jobs:
  ci_build:
    env:
      DBT_PWD: ${{ secrets.DBT_PWD }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SLIM_CI_SERVICE_ACCOUNT_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SLIM_CI_SERVICE_ACCOUNT_SECRET }}
      CI_SCHEMA: "CI_PR_${{ github.event.pull_request.id }}"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Python setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: install-requirements
        run: |
          pip install dbt==0.21.0

          # install packages
          dbt deps

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::743265699366:role/bi-learning-slimci-role
          aws-region: eu-west-1
          role-duration-seconds: 1200

      - name: Fetch prod manifest from s3
        run: aws s3 cp s3://bi-training-fission-slimci/manifest.json ./prod_manifest/manifest.json

#      - name: list modified dbt models
#        id: dbt_ls
#        run: echo "::set-output name=modified_models::$(dbt ls --select state:modified+ --state ./prod_manifest --resource-type model --output path --profiles-dir . --profile fission --target prod)"

#      - name: sqlfluff
#        run: echo "${{ steps.dbt_ls.outputs.modified_models }}"

      - name: Run seeds
        run: dbt seed --profiles-dir . --profile fission -s state:modified --state ./prod_manifest

      - name: Run all models
        run: dbt run --profiles-dir . --profile fission -s state:modified+ --state ./prod_manifest --defer

      - name: Run all tests
        run: dbt test --exclude test_name:relationships --profiles-dir . --profile fission -s state:modified+ --state ./prod_manifest --defer
